name: Po Analytics - Pollen Trend Analysis

on:
  schedule:
    - cron: '0 21 1,8,15,22 * *'  # 毎月1日、8日、15日、22日の朝6時（日本時間）
  workflow_dispatch:

jobs:
  analyze-and-tweet:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd pollen-analytics
        pip install -r requirements.txt
    - name: Run pollen trend analysis
      env:
        POLLEN_TWITTER_BEARER_TOKEN: ${{ secrets.POLLEN_TWITTER_BEARER_TOKEN }}
        POLLEN_TWITTER_API_KEY: ${{ secrets.POLLEN_TWITTER_API_KEY }}
        POLLEN_TWITTER_API_SECRET: ${{ secrets.POLLEN_TWITTER_API_SECRET }}
        POLLEN_TWITTER_ACCESS_TOKEN: ${{ secrets.POLLEN_TWITTER_ACCESS_TOKEN }}
        POLLEN_TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.POLLEN_TWITTER_ACCESS_TOKEN_SECRET }}
      run: |
        cd pollen-analytics
        python main.py
